local helpers = require("plenary.test_harness")
local commands = require("manager.commands")

describe("Commands Module", function()
    it("should register custom commands", function()
        commands.setup()
        local ok, _ = pcall(vim.api.nvim_command, "ManagerCommand")
        assert.is_true(ok, "Custom command ManagerCommand not registered")
    end)

    it("should execute a command successfully", function()
        commands.setup()
        vim.api.nvim_command("ManagerCommand arg1 arg2")
        assert.are.equal("arg1", commands.last_args[1], "First argument was not passed correctly")
        assert.are.equal("arg2", commands.last_args[2], "Second argument was not passed correctly")
    end)

    it("should handle invalid arguments gracefully", function()
        commands.setup()
        assert.has_error(function()
            vim.api.nvim_command("ManagerCommand invalid")
        end, "Command did not throw an error for invalid input")
    end)
end)
