local helpers = require("plenary.test_harness")
local navigation = require("manager.navigation")

describe("Navigation Module", function()
    it("should navigate to the next window", function()
        vim.cmd("vsplit")
        local current_win = vim.api.nvim_get_current_win()
        navigation.next_window()
        assert.are_not.equal(current_win, vim.api.nvim_get_current_win(), "Did not navigate to the next window")
    end)

    it("should return an error if only one window exists", function()
        assert.has_error(function()
            navigation.next_window()
        end, "Did not throw error when no other windows exist")
    end)

    it("should navigate back to the previous window", function()
        vim.cmd("vsplit")
        local current_win = vim.api.nvim_get_current_win()
        navigation.next_window()
        navigation.prev_window()
        assert.are.equal(current_win, vim.api.nvim_get_current_win(), "Did not navigate back to the previous window")
    end)
end)
