local helpers = require("plenary.test_harness")
local split = require("manager.split")

describe("Split Module", function()
    it("should create a vertical split", function()
        local win = split.create_vertical()
        assert.is_true(vim.api.nvim_win_is_valid(win), "Vertical split is invalid")
    end)

    it("should create a horizontal split", function()
        local win = split.create_horizontal()
        assert.is_true(vim.api.nvim_win_is_valid(win), "Horizontal split is invalid")
    end)

    it("should resize a split", function()
        local win = split.create_vertical()
        split.resize(win, 40)
        local width = vim.api.nvim_win_get_width(win)
        assert.are.equal(40, width, "Width was not resized correctly")
    end)

    it("should handle invalid resize gracefully", function()
        local win = split.create_vertical()
        assert.has_error(function()
            split.resize(win, -10)
        end, "Did not throw error for invalid resize")
    end)
end)
